---
name: Feature Request
about: Suggest a new feature for the survivor project
title: '[FEATURE] '
labels: enhancement
assignees: ''
---

## Feature Description
A clear and concise description of the feature you want to implement.

## User Story
As a [type of user], I want [goal] so that [benefit].

## Acceptance Criteria
- [ ] Criterion 1
- [ ] Criterion 2
- [ ] Criterion 3

## Technical Requirements
- API integration requirements
- Database considerations
- Frontend/Backend requirements
- Responsive design requirements
- Accessibility requirements

## Priority
- [ ] High
- [ ] Medium
- [ ] Low

## Area
- [ ] Public Area
- [ ] Admin Area
- [ ] Startup Area
- [ ] Technical Infrastructure

## Additional Context
Add any other context or screenshots about the feature request here.