FROM alpine:3.22.1

WORKDIR /server

RUN apk update && apk add nodejs npm

COPY ./backend/package.json ./
COPY ./backend ./

RUN ls -aR
RUN npm install

EXPOSE 4242

# Remove already existing node_modules dir
RUN [ -d "node_modules" ] && rm -rf node_modules
ENTRYPOINT ["node", "app.js"]
