openapi: 3.0.0
info:
  title: JEB Incubator
  version: 1.0.0

servers:
  - url: http://localhost:4242

paths:
  /auth/signup:
    post:
      summary: Register a new startup
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Bad request

  /auth/login:
    post:
      summary: Login as a startup
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials

components:
  schemas:
    SignupRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    AuthResponse:
      type: object
      properties:
        token:
          type: string

    Startup:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        password:
          type: string
        legalStatus:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
        phone:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
          nullable: true
        description:
          type: string
          nullable: true
        websiteUrl:
          type: string
          nullable: true
        socialMediaUrl:
          type: string
          nullable: true
        projectStatus:
          type: string
          nullable: true
        needs:
          type: array
          items:
            type: string
        sector:
          type: string
          nullable: true
        maturity:
          type: string
          nullable: true
        founders:
          type: array
          items:
            type: object
